apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-deployment
spec:
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - image: flask-api
        name: flask-api
        imagePullPolicy: Never
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
spec:
  type: LoadBalancer
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000