apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-deployment
spec:
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - image: europe-north1-docker.pkg.dev/august-tesla-333012/video-api/flask-api:v61
        name: flask-api
        ports:
          - containerPort: 5000
        resources:
            requests:
              cpu: "150m"
            limits:
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
spec:
  type: LoadBalancer
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000