apiVersion: v1
kind: PersistentVolume
metadata:
  name: video-pv
  labels:
    type: gcePersistentDisk
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    name: video-storage
    path: 10.216.28.202

